name: "awesome-stargazers"
description: "Github Action that will update the stargazer count for all Github Repos found in an awesome-list Readme files"
author: "Florian Roessler"
inputs:
  myReadme:
    description: "alternative location of Readme file"
    default: "readme.md"
runs:
  using: "docker"
  image: "Dockerfile"
